LogDir: /tmp
Debug: false
Daemon: true
# ProxyURI:
# CAPath: /etc/ssl/certs
# CAFile: /opt/local/share/curl/curl-ca-bundle.crt    # for MacPorts
# CAFile: /etc/ssl/certs/ca-certificates.crt          # for Debian

Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

NMA:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Growl:
  Sticky: 0    # lowest priority to enable stikcy option

Pushbullet:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 DeviceIden: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Accounts:
 -
  Application: "Twitter"
  NotifyMethods:
    - "prowl" # Prowl for iPhone
    - "pushbullet" #Pushbullet
#   - "nma"   # Notify My Android for Android
#   - "growl" # use growlnotify, it requires growl.gem and growlnotify
  User: example_username
  UseProxy: false          # <= use Prowl::ProxyURL
  Mentions:                # Event on Mentions
    Enable: true
    Priority: 1
    IgnoreSelf: false      # Ignore mention by myself
  Direct:                  # Event on Direct Messages
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore DM event from myself
  Retweets:                # Event on Retweets
    Enable: true
    Priority: 0
  Membership:              # Event on List Membership
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore remove event
  Favorite:                # Event on Favorite/Unfavorite
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore Unfavorite event
  Unfollowed:              # Event on Unfollowed, requiresi API rate
    Enable: true
    Priority: 0
    Interval: 1800
  RegexpMatch:
    -
      User: "eew_jp"
      Priority: 2
      Enable: true
    -
      Text: "TwiProwl"
      Priority: 0
      Enable: true
    -
      User: "^northeye$"
      Text: "TwiProwl|twiprowl"
